create table apz_ocpn
(
    code          varchar(50) not null
        constraint apz_ocpn_pkey
            primary key,
    name          varchar(100),
    fr_name       varchar(100),
    vat_reg_num   varchar(12),
    industry      varchar(20),
    business      varchar(20),
    address       varchar(254),
    status        varchar(1) default 'A'::character varying(1),
    user_sign     smallint,
    user_sign2    smallint,
    create_date   date,
    create_time   smallint,
    update_date   date,
    update_time   smallint,
    dfl_cust      varchar(15),
    dfl_vendor    varchar(15),
    dfl_whs       varchar(8),
    dfl_tax_code  varchar(8),
    street        varchar(100),
    building      varchar(100),
    zip_code      varchar(20),
    block         varchar(100),
    city          varchar(100),
    state         varchar(3),
    county        varchar(100),
    country       varchar(3),
    email         varchar(254),
    phone1        varchar(20),
    phone2        varchar(20),
    fax           varchar(20),
    main_currency varchar(3),
    sys_currency  varchar(3),
    sum_dec       smallint,
    qty_dec       smallint,
    price_dec     smallint,
    rate_dec      smallint,
    percent_dec   smallint,
    measure_dec   smallint,
    time_format   varchar(20),
    date_format   varchar(20),
    date_sep      varchar(1),
    dec_sep       varchar(1),
    thous_sep     varchar(1),
    neg_whs       varchar(1) default 'Y'::character varying,
    website       varchar(254)
);
