-- Table: apz_ovpm

-- DROP TABLE apz_ovpm;

CREATE TABLE apz_ovpm
(
    doc_entry integer NOT NULL,
    doc_num integer NOT NULL,
    doc_type character(1) COLLATE pg_catalog."default",
    canceled character(1) COLLATE pg_catalog."default",
    handwrtten character(1) COLLATE pg_catalog."default",
    printed character(1) COLLATE pg_catalog."default",
    doc_date date,
    doc_due_date date,
    card_code character varying(15) COLLATE pg_catalog."default",
    card_name character varying(100) COLLATE pg_catalog."default",
    address character varying(254) COLLATE pg_catalog."default",
    ddct_prcnt numeric(19,6),
    ddct_sum numeric(19,6),
    ddct_sumfc numeric(19,6),
    cash_acct character varying(15) COLLATE pg_catalog."default",
    cash_sum numeric(19,6),
    cash_sumfc numeric(19,6),
    credit_sum numeric(19,6),
    cred_sumfc numeric(19,6),
    check_acct character varying(15) COLLATE pg_catalog."default",
    check_sum numeric(19,6),
    check_sumfc numeric(19,6),
    trsfr_acct character varying(15) COLLATE pg_catalog."default",
    trsfr_sum numeric(19,6),
    trsfr_sumfc numeric(19,6),
    trsfr_date date,
    trsfr_ref character varying(27) COLLATE pg_catalog."default",
    pay_no_doc character(1) COLLATE pg_catalog."default",
    no_doc_sum numeric(19,6),
    no_doc_sumfc numeric(19,6),
    doc_curr character varying(3) COLLATE pg_catalog."default",
    diff_curr character(1) COLLATE pg_catalog."default",
    doc_rate numeric(19,6),
    sys_rate numeric(19,6),
    doc_total numeric(19,6),
    doc_totalfc numeric(19,6),
    ref1 character varying(11) COLLATE pg_catalog."default",
    ref2 character varying(8) COLLATE pg_catalog."default",
    counter_ref character varying(8) COLLATE pg_catalog."default",
    comments character varying(254) COLLATE pg_catalog."default",
    jrnl_memo character varying(50) COLLATE pg_catalog."default",
    trans_id integer,
    doc_time smallint,
    show_at_card character(1) COLLATE pg_catalog."default",
    spilt_trans character(1) COLLATE pg_catalog."default",
    create_tran character(1) COLLATE pg_catalog."default",
    flags integer,
    cntct_code integer,
    ddct_sumsy numeric(19,6),
    cash_sumsy numeric(19,6),
    cred_sumsy numeric(19,6),
    check_sumsy numeric(19,6),
    trsfr_sumsy numeric(19,6),
    nodoc_sumsy numeric(19,6),
    doc_totalsy numeric(19,6),
    obj_type character varying(20) COLLATE pg_catalog."default",
    storno_rate numeric(19,6),
    update_date date,
    create_date date,
    apply_vat character(1) COLLATE pg_catalog."default",
    tax_date date,
    series integer,
    confirmed character(1) COLLATE pg_catalog."default",
    show_jdt character(1) COLLATE pg_catalog."default",
    bank_code character varying(30) COLLATE pg_catalog."default",
    bank_acct character varying(50) COLLATE pg_catalog."default",
    data_source character(1) COLLATE pg_catalog."default",
    user_sign smallint,
    log_instanc integer,
    vat_group character varying(8) COLLATE pg_catalog."default",
    vat_sum numeric(19,6),
    vat_sumfc numeric(19,6),
    vat_sumsy numeric(19,6),
    finnc_priod integer,
    vat_prcnt numeric(19,6),
    dcount numeric(19,6),
    dcnt_sum numeric(19,6),
    dcnt_sumfc numeric(19,6),
    dcnt_sumsy numeric(19,6),
    splt_credln character(1) COLLATE pg_catalog."default",
    prj_code character varying(20) COLLATE pg_catalog."default",
    payment_ref character varying(27) COLLATE pg_catalog."default",
    submitted character(1) COLLATE pg_catalog."default",
    status character(1) COLLATE pg_catalog."default",
    pay_mth character varying(15) COLLATE pg_catalog."default",
    bank_countr character varying(3) COLLATE pg_catalog."default",
    freight_sum numeric(19,6),
    freigt_fc numeric(19,6),
    freigt_sc numeric(19,6),
    boe_acc character varying(15) COLLATE pg_catalog."default",
    boe_num integer,
    boe_sum numeric(19,6),
    boe_sumfc numeric(19,6),
    boe_sumsc numeric(19,6),
    boe_agent character varying(32) COLLATE pg_catalog."default",
    boe_status character(1) COLLATE pg_catalog."default",
    wt_code character varying(4) COLLATE pg_catalog."default",
    wt_sum numeric(19,6),
    wt_sum_frgn numeric(19,6),
    wt_sum_sys numeric(19,6),
    wt_account character varying(15) COLLATE pg_catalog."default",
    wt_baseamnt numeric(19,6),
    proforma character(1) COLLATE pg_catalog."default",
    boe_abs integer,
    bp_act character varying(15) COLLATE pg_catalog."default",
    bcg_sum numeric(19,6),
    bcg_sumfc numeric(19,6),
    bcg_sumsy numeric(19,6),
    pindicator character varying(10) COLLATE pg_catalog."default" NOT NULL,
    pa_priority character(1) COLLATE pg_catalog."default",
    pay_to_code character varying(50) COLLATE pg_catalog."default",
    is_payto_bnk character(1) COLLATE pg_catalog."default",
    pbnk_cnt character varying(3) COLLATE pg_catalog."default",
    pbnk_code character varying(30) COLLATE pg_catalog."default",
    pbnk_accnt character varying(50) COLLATE pg_catalog."default",
    pbnk_branch character varying(50) COLLATE pg_catalog."default",
    wiz_dun_blck character(1) COLLATE pg_catalog."default",
    wt_base_sum numeric(19,6),
    wt_base_sumf numeric(19,6),
    wt_base_sums numeric(19,6),
    und_ov_diff numeric(19,6),
    und_ov_diffs numeric(19,6),
    bank_act_key integer,
    version_num character varying(11) COLLATE pg_catalog."default",
    vat_date date,
    trans_code character varying(4) COLLATE pg_catalog."default",
    paym_type character(1) COLLATE pg_catalog."default",
    tfr_real_amt numeric(19,6),
    cancel_date date,
    open_bal numeric(19,6),
    open_balfc numeric(19,6),
    open_balsc numeric(19,6),
    bcg_taxsum numeric(19,6),
    bcg_taxsumf numeric(19,6),
    bcg_taxsums numeric(19,6),
    tpw_id integer,
    challan_no character varying(32) COLLATE pg_catalog."default",
    challan_bak character varying(60) COLLATE pg_catalog."default",
    challan_dat date,
    wdd_status character(1) COLLATE pg_catalog."default",
    bcg_vat_grp character varying(8) COLLATE pg_catalog."default",
    bcg_vat_pcnt numeric(19,6),
    seq_code smallint,
    serial integer,
    series_str character varying(3) COLLATE pg_catalog."default",
    sub_str character varying(3) COLLATE pg_catalog."default",
    bsr_code character varying(25) COLLATE pg_catalog."default",
    loc_code integer,
    wt_onhld_pst numeric(19,6),
    user_sign2 smallint,
    build_desc character varying(50) COLLATE pg_catalog."default",
    residen_num character(1) COLLATE pg_catalog."default",
    operat_code character(1) COLLATE pg_catalog."default",
    und_ov_difff numeric(19,6),
    mi_entry integer,
    free_text1 character varying(254) COLLATE pg_catalog."default",
    free_text2 character varying(254) COLLATE pg_catalog."default",
    free_text3 character varying(254) COLLATE pg_catalog."default",
    show_doc_no character(1) COLLATE pg_catalog."default",
    tds_interst numeric(19,6),
    tds_charges numeric(19,6),
    cup integer,
    cig integer,
    mi_type character varying(20) COLLATE pg_catalog."default",
    suppl_code character varying(254) COLLATE pg_catalog."default",
    bpl_id integer,
    bpl_name character varying(100) COLLATE pg_catalog."default",
    vat_reg_num character varying(32) COLLATE pg_catalog."default",
    bpl_cent_pmt character(1) COLLATE pg_catalog."default",
    draft_key integer,
    tds_fee numeric(19,6),
    min_headcl integer,
    sepa_date date,
    owner_code integer,
    agr_no integer,
    create_ts integer,
    update_ts integer,
    tds_type character(1) COLLATE pg_catalog."default",
    dr_no character varying(32) COLLATE pg_catalog."default",
    pmntwt_cert character(1) COLLATE pg_catalog."default",
    enpbnk_acct text COLLATE pg_catalog."default",
    encrypt_iv character varying(100) COLLATE pg_catalog."default",
    dpp_status character(1) COLLATE pg_catalog."default",
    price_mode character(1) COLLATE pg_catalog."default",
    u_jvnumber character varying(30) COLLATE pg_catalog."default",
    u_payer character varying(100) COLLATE pg_catalog."default",
    u_payadd character varying(100) COLLATE pg_catalog."default",
    u_countref character varying(50) COLLATE pg_catalog."default",
    u_bankacct character varying(50) COLLATE pg_catalog."default",
    u_bankname character varying(254) COLLATE pg_catalog."default",
    u_chinhanh character varying(50) COLLATE pg_catalog."default",
    u_status character varying(20) COLLATE pg_catalog."default",
    u_bom character varying(50) COLLATE pg_catalog."default",
    u_idhdv character varying(30) COLLATE pg_catalog."default",
    u_iddtt character varying(10) COLLATE pg_catalog."default",
    u_isexport character(1) COLLATE pg_catalog."default",
    CONSTRAINT apz_ovpm_pkey PRIMARY KEY (doc_entry)
)

TABLESPACE pg_default;