CREATE TABLE apz_oivl
(
    trans_seq integer NOT NULL DEFAULT 0,
    trans_type integer DEFAULT '-1'::integer,
    create_by integer,
    obj_type character varying(20) COLLATE pg_catalog."default",
    doc_entry integer,
    line_num integer,
    doc_date date,
    create_time smallint,
    item_code character varying(50) COLLATE pg_catalog."default",
    in_qty numeric(19,6),
    out_qty numeric(19,6),
    price numeric(19,6),
    currency character varying(3) COLLATE pg_catalog."default",
    rate numeric(19,6),
    create_date date,
    whs_code character varying(8) COLLATE pg_catalog."default",
    user_sign smallint,
    date_source character varying(1) COLLATE pg_catalog."default" DEFAULT 'N'::character varying,
    post_status character varying COLLATE pg_catalog."default" DEFAULT 'N'::character varying,
    sum_stock numeric(19,6),
    open_qty numeric(19,6),
    tree_id integer DEFAULT '-1'::integer,
    parent_id integer DEFAULT '-1'::integer,
    version_num character varying(11) COLLATE pg_catalog."default",
    qty numeric(19,6),
    unit_msr character varying(50) COLLATE pg_catalog."default",
    ugp_entry smallint,
    uom_code character varying(50) COLLATE pg_catalog."default",
    num_per_msr numeric(19,6),
    price_list smallint,
    item_cost numeric(19,6),
    table_id integer,
    card_code character varying(15) COLLATE pg_catalog."default",
    inv_qty numeric(19,6),
    open_inv_qty numeric(19,6),
    company character varying(50) COLLATE pg_catalog."default",
    base_type character varying(20) COLLATE pg_catalog."default",
    base_entry integer,
    base_line integer,
    target_type character varying(20) COLLATE pg_catalog."default",
    target_entry integer,
    target_line integer,
    action_type character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT apz_oivl_primary PRIMARY KEY (trans_seq)
);