create table apz_oitm
(
    item_code      varchar(50) not null
        constraint apz_oitm_pkey
            primary key,
    item_name      varchar(254),
    itms_grp_cod   varchar(50),
    item_type      varchar(3) default 'N'::character varying,
    prchse_item    varchar(1),
    sell_item      varchar(1),
    invn_item      varchar(1),
    on_hand        numeric(19, 6),
    is_commited    numeric(19, 6),
    on_order       numeric(19, 6),
    dfltwh         varchar(8),
    buy_unit_msr   varchar(100),
    num_in_buy     numeric(19, 6),
    sal_unit_msr   varchar(100),
    num_in_sale    numeric(19, 6),
    invn_unit_msr  varchar(100),
    user_sign      smallint,
    user_sign2     smallint,
    asset_item     varchar(1),
    height         numeric(19, 6),
    height_unit    varchar(100),
    width          numeric(19, 6),
    width_unit     varchar(100),
    length         numeric(19, 6),
    length_unit    varchar(100),
    weight         numeric(19, 6),
    weight_unit    varchar(100),
    avg_price      numeric(19, 6),
    status         varchar(1) default 'A',
    valid_from     date,
    valid_to       date,
    frozen_for     varchar(1),
    frozen_from    date,
    frozen_to      date,
    ship_type      smallint,
    lead_time      integer,
    series         integer,
    atc_entry      integer,
    attachment     text,
    create_date    date,
    update_date    date,
    create_time    smallint,
    update_time    smallint,
    tramrk         varchar(50),
    barcode        varchar(254),
    remarks        varchar,
    item_tags      varchar(500),
    vat_group      varchar(50),
    last_pur_prc   numeric(19, 6),
    ugp_entry      integer,
    location       varchar(254),
    f_itm_code     varchar(50),
    s_uom_entry    varchar(50),
    p_uom_entry    varchar(50),
    i_uom_entry    varchar(50),
    line_id        smallint,
    qrcode         varchar(50),
    property1_name varchar(254),
    property1      varchar(50),
    property2_name varchar(254),
    property2      varchar(50),
    property3_name varchar(254),
    property3      varchar(50),
    property_item  varchar(1),
    property_count smallint,
    data_source    varchar(1) default 'N'::character varying
);

alter table apz_oitm
    owner to "POSMAN";

