CREATE TABLE form_setting_user
(
    column_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    column_name character varying(254) COLLATE pg_catalog."default",
    data_type character varying(50) COLLATE pg_catalog."default",
    sub_type character varying(50) COLLATE pg_catalog."default",
    maximum_length smallint,
    is_visible character varying(1) COLLATE pg_catalog."default",
    is_editable character varying(1) COLLATE pg_catalog."default",
    is_required character varying(1) COLLATE pg_catalog."default",
    default_value character varying(254) COLLATE pg_catalog."default",
    is_udf character varying(1) COLLATE pg_catalog."default",
    view_group smallint,
    view_order smallint,
    linked_type character varying(2) COLLATE pg_catalog."default",
    linked_object character varying(20) COLLATE pg_catalog."default",
    create_date date,
    create_time smallint,
    update_date date,
    update_time smallint,
    user_sign smallint,
    user_sign2 smallint,
    setting_entry integer NOT NULL,
    user_id smallint NOT NULL,
    col_fixed character varying(1) COLLATE pg_catalog."default" DEFAULT 'N'::character varying,
    col_width integer,
    col_height integer,
    is_ch_edit character varying(1) COLLATE pg_catalog."default" DEFAULT 'Y'::character varying,
    is_ch_visible character varying(1) COLLATE pg_catalog."default" DEFAULT 'Y'::character varying,
    CONSTRAINT form_setting_user_pkey1 PRIMARY KEY (user_id, setting_entry, column_id)
);