CREATE TABLE general_setting
(
    domain character varying(100) COLLATE pg_catalog."default",
    version character varying(50) COLLATE pg_catalog."default",
    company_name character varying(254) COLLATE pg_catalog."default",
    email character varying(254) COLLATE pg_catalog."default",
    phone1 character varying(20) COLLATE pg_catalog."default",
    phone2 character varying(20) COLLATE pg_catalog."default",
    address character varying(254) COLLATE pg_catalog."default",
    company_type character(1) COLLATE pg_catalog."default",
    create_date date,
    create_time integer,
    update_date date,
    update_time integer,
    country character varying(3) COLLATE pg_catalog."default",
    fax character varying(20) COLLATE pg_catalog."default",
    main_currency character varying(3) COLLATE pg_catalog."default",
    sys_currency character varying(3) COLLATE pg_catalog."default",
    sum_dec smallint,
    qty_dec smallint,
    price_dec smallint,
    rate_dec smallint,
    percent_dec smallint,
    measure_dec smallint,
    time_format character(1) COLLATE pg_catalog."default",
    date_format character(1) COLLATE pg_catalog."default",
    date_sep character(1) COLLATE pg_catalog."default",
    dec_sep character(1) COLLATE pg_catalog."default",
    thous_sep character(1) COLLATE pg_catalog."default",
    neg_whs character(1) COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    atc_entry integer,
    locale character varying(10) COLLATE pg_catalog."default",
    def_cust character varying(50) COLLATE pg_catalog."default",
    is_shift character(1) COLLATE pg_catalog."default",
    is_aut_prt_bill character(1) COLLATE pg_catalog."default",
    dis_cod character(1) COLLATE pg_catalog."default",
    dis_card character(1) COLLATE pg_catalog."default",
    dis_tranf character(1) COLLATE pg_catalog."default",
    max_history bigint,
    chg_sal_prlist character varying COLLATE pg_catalog."default" DEFAULT 'N'::character varying,
    user_sign smallint
)

TABLESPACE pg_default;