USE [SBO_TKMB_GOLIVE]
GO

/****** Object:  Table [dbo].[@ITEMLOG1]    Script Date: 4/14/2021 4:20:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[@ITEMLOG1](
	[Code] [nvarchar](50) NOT NULL,
	[LineId] [int] NOT NULL,
	[Object] [nvarchar](20) NULL,
 CONSTRAINT [KITEMLOG1_PR] PRIMARY KEY CLUSTERED 
(
	[Code] ASC,
	[LineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


