USE [SBO_TKMB_GOLIVE]
GO

/****** Object:  Table [dbo].[@LNV]    Script Date: 4/14/2021 4:19:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[@LNV](
	[Code] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](100) NOT NULL
 CONSTRAINT [KLNV_PR] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


